name: ${name}
version: ${project.version}
description: ${description}
author: moose517
website: ${url}

main: com.moosemanstudios.Birthdays.Bukkit.Birthdays

commands:
    birthdays:
        description: General command
        aliases: bdays
permissions:
    birthdays.update:
        description: Allows for updating of plugin
    birthdays.admin:
        description: All general admin permissions
        children:
            birthdays.update: true