name: ${name}
version: ${project.version}
description: ${description}
author: moose517
website: ${url}

main: com.moosemanstudios.Birthdays.Bukkit.Birthdays

commands:
    birthdays:
        description: General command
        aliases: bdays
permissions:
    birthdays.update:
        description: Allows for updating of plugin
    birthdays.reload.config:
        description: Allow reloading of config file
    birthdays.reload.all:
        description: Access to all reload commands
        children:
            birthdays.reload.config: true
    birthdays.admin:
        description: All general admin permissions
        children:
            birthdays.update: true
            birthdays.reload.*: true