name: ${name}
version: ${project.version}
description: ${description}
author: moose517
main: com.moosemanstudios.Birthdays.Bukkit.Birthdays
commands:
    birthday:
        description: General command
permissions:
    birthdays.admin:
        description: General Admin permission node