name: Birthdays
version: 1.2
description: Give Players presents on their birthday!
author: moose517
website: http://www.moosemanstudios.com

main: com.moosemanstudios.Birthdays.Bukkit.Birthdays

commands:
    birthdays:
        description: General command
        aliases: bdays
permissions:
    birthdays.update:
        description: Allows for updating of plugin
    birthdays.set:
        description: Allows for adjusting player birthdays
    birthdays.reload.config:
        description: Allow reloading of config file
    birthdays.reload.players:
        description: Allow reloading of players file
    birthdays.reload.all:
        description: Access to all reload commands
        children:
            birthdays.reload.config: true
            birthdays.reload.players: true
    birthdays.admin:
        description: All general admin permissions
        children:
            birthdays.update: true
            birthdays.reload.all: true
            birthdays.set: true